# 1. Prepare JSON files and directories
libname: "logic_generated" # 라이브러리 이름
cellname: "dff_2x" # cell 이름

# libname: "scan_generated" # 라이브러리 이름
# cellname: "scan_cell" # cell 이름

# libname: "logic_generated" # 라이브러리 이름
# cellname: "dff_2x" # cell 이름

db_dir: "db" # laygo 에서 export된 json db 저장 경로

# in/output configuration setting 
metal_dir: "out/metal"
via_dir: "out/via"
visualized_dir: "out/visualized"
log_dir: "out/log"

netlog_dir: "out/label"

config_file_path: "config/config_tsmcN28.yaml"
