# 1. Prepare JSON files and directories
# libname: "scan_generated" # 라이브러리 이름
# cellname: "scan_chain_33bit_2row" # cell 이름

# libname: "scan_generated" # 라이브러리 이름
# cellname: "scan_cell" # cell 이름

libname: "scan_generated" # 라이브러리 이름
cellname: "scan_cell" # cell 이름

db_dir: "db"
metal_dir: "out/metal"
via_dir: "out/via"
visualized_dir: "out/visualized"

netlog_dir: "out/label"

config_file_path: "config/config.yaml"
